/**
 * @class       : ScreenName
 * @author      : vikash (vikash@kritikal-Latitude-3480)
 * @created     : Wednesday Jan 02, 2019 12:38:00 IST
 * @description : ScreenName
 */

export default class ScreenName {
  static DASHBOARD_HOME = 'DASHBOARD_HOME';
  static DASHBOARD_RETAILER_DEMO_HOME = 'DASHBOARD_RETAILER_DEMO_HOME';
  static DASHBOARD_SCAN_QRCODE = 'DASHBOARD_SCAN_QRCODE';
  static DASHBOARD_SUBMIT_QRCODE_STATUS = 'DASHBOARD_SUBMIT_QRCODE_STATUS';
  static DASHBOARD_QRCODE_HISTORY = 'DASHBOARD_QRCODE_HISTORY';
  static DASHBOARD_QRCODE_HISTORY_DATEWISE = 'DASHBOARD_QRCODE_HISTORY_DATEWISE';
  static DASHBOARD_QRCODE_HISTORY_TIMEWISE = 'DASHBOARD_QRCODE_HISTORY_TIMEWISE';
  static DASHBOARD_QRCODE_STATEMENT = 'DASHBOARD_QRCODE_STATEMENT';
  static DASHBOARD_CONTACTUS = 'DASHBOARD_CONTACTUS';
  static DASHBOARD_REGISTER_COMPLAINT = 'DASHBOARD_REGISTER_COMPLAINT';
  static DASHBOARD_ABOUTUS = 'DASHBOARD_ABOUTUS';
  static DASHBOARD_MY_PROFILE = 'DASHBOARD_MY_PROFILE';
  static DASHBOARD_RETAILER_SIGNUP = 'DASHBOARD_RETAILER_SIGNUP';
  static DASHBOARD_RETAILER_VERIY_OTP = 'DASHBOARD_RETAILER_VERIY_OTP';
  static DASHBOARD_FREEDOM_FORTUNE = 'DASHBOARD_FREEDOM_FORTUNE';
  static DASHBOARD_NOTIFICATION = 'DASHBOARD_NOTIFICATION';
  static DASHBOARD_GIFTING = 'DASHBOARD_GIFTING';
  static DASHBOARD_BANK = 'DASHBOARD_BANK';
  static DASHBOARD_STATUS_SUMMARY = 'DASHBOARD_STATUS_SUMMARY';
  static DASHBOARD_QRCODE_PRE_SCAN_SUMMARY = 'DASHBOARD_QRCODE_PRE_SCAN_SUMMARY';
}

